#pragma once

#include "Command.h"
#include "SipmRegister.h"

INDEXED_ENUM(SipmControlReadCommand,
    HV_ENABLE,                  
    MODE,                       
    V_TARGET_WRITE,             
    RAMP_SPEED,                 
    MAX_V,                      
    MAX_I,                      
    C_TEMP_M2,                  
    C_TEMP_M,                   
    C_TEMP_Q,                   
    ALFA_VOUT,	                
    ALFA_IOUT,	                
    ALFA_VREF,	                
    ALFA_TREF,	                
    TCOEF,                      
    LUT_ENABLE,                 
    ENABLE_PI,                  
    LUT_ADDRESS,                
    LUT_PROGRAM_TEMPERATURE,    
    LUT_PROGRAM_OUTPUT_VALUE,   
    LUT_LENGTH,                 
    I2C_BASE_ADDRESS,           
    CURRENT_RANGE,              
    PIN_STATUS,                 
    VIN,                        
    VOUT,	                    
    IOUT,	                    
    VREF,	                    
    TREF,	                    
    V_TARGET_READ,              
    R_TARGET,                   
    CVT,                        
    COMPLIANCE_V,               
    COMPLIANCE_I,               
    PRODUCT_CODE,               
    FW_VERSION,                 
    HW_VERSION,                 
    SERIAL_NUMBER              
)

constexpr inline auto SipmControlReadTable = CommandEnumTable<SipmControlReadCommandIndexer, 0>::make_table(
    std::pair(SipmControlReadCommand::HV_ENABLE,                  std::tuple("HV_ENABLE",                 DataFormatTypes<0>{}, DataFormat::Bool , "[DISABLED]")),
    std::pair(SipmControlReadCommand::MODE,                       std::tuple("MODE",                      DataFormatTypes<0>{}, DataFormat::Int  , "[DISABLED]")),
    std::pair(SipmControlReadCommand::V_TARGET_WRITE,             std::tuple("V_TARGET_WRITE",            DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::RAMP_SPEED,                 std::tuple("RAMP_SPEED",                DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::MAX_V,                      std::tuple("MAX_V",                     DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::MAX_I,                      std::tuple("MAX_I",                     DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::C_TEMP_M2,                  std::tuple("C_TEMP_M2",                 DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::C_TEMP_M,                   std::tuple("C_TEMP_M",                  DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::C_TEMP_Q,                   std::tuple("C_TEMP_Q",                  DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::ALFA_VOUT,	              std::tuple("ALFA_VOUT",	              DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::ALFA_IOUT,	              std::tuple("ALFA_IOUT",	              DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::ALFA_VREF,	              std::tuple("ALFA_VREF",	              DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::ALFA_TREF,	              std::tuple("ALFA_TREF",	              DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::TCOEF,                      std::tuple("TCOEF",                     DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::LUT_ENABLE,                 std::tuple("LUT_ENABLE",                DataFormatTypes<0>{}, DataFormat::Bool , "[DISABLED]")),
    std::pair(SipmControlReadCommand::ENABLE_PI,                  std::tuple("ENABLE_PI",                 DataFormatTypes<0>{}, DataFormat::Bool , "[DISABLED]")),
    std::pair(SipmControlReadCommand::LUT_ADDRESS,                std::tuple("LUT_ADDRESS",               DataFormatTypes<0>{}, DataFormat::Int  , "[DISABLED]")),
    std::pair(SipmControlReadCommand::LUT_PROGRAM_TEMPERATURE,    std::tuple("LUT_PROGRAM_TEMPERATURE",   DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::LUT_PROGRAM_OUTPUT_VALUE,   std::tuple("LUT_PROGRAM_OUTPUT_VALUE",  DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::LUT_LENGTH,                 std::tuple("LUT_LENGTH",                DataFormatTypes<0>{}, DataFormat::Int  , "[DISABLED]")),
    std::pair(SipmControlReadCommand::I2C_BASE_ADDRESS,           std::tuple("I2C_BASE_ADDRESS",          DataFormatTypes<0>{}, DataFormat::Int  , "[DISABLED]")),
    std::pair(SipmControlReadCommand::CURRENT_RANGE,              std::tuple("CURRENT_RANGE",             DataFormatTypes<0>{}, DataFormat::Int  , "[DISABLED]")),
    std::pair(SipmControlReadCommand::PIN_STATUS,                 std::tuple("PIN_STATUS",                DataFormatTypes<0>{}, DataFormat::Int  , "[DISABLED]")),
    std::pair(SipmControlReadCommand::VIN,                        std::tuple("VIN",                       DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::VOUT,	                      std::tuple("VOUT",	                  DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::IOUT,	                      std::tuple("IOUT",	                  DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::VREF,	                      std::tuple("VREF",	                  DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::TREF,	                      std::tuple("TREF",	                  DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::V_TARGET_READ,              std::tuple("V_TARGET_READ",             DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::R_TARGET,                   std::tuple("R_TARGET",                  DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::CVT,                        std::tuple("CVT",                       DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::COMPLIANCE_V,               std::tuple("COMPLIANCE_V",              DataFormatTypes<0>{}, DataFormat::Bool , "[DISABLED]")),
    std::pair(SipmControlReadCommand::COMPLIANCE_I,               std::tuple("COMPLIANCE_I",              DataFormatTypes<0>{}, DataFormat::Bool , "[DISABLED]")),
    std::pair(SipmControlReadCommand::PRODUCT_CODE,               std::tuple("PRODUCT_CODE",              DataFormatTypes<0>{}, DataFormat::Int  , "[DISABLED]")),
    std::pair(SipmControlReadCommand::FW_VERSION,                 std::tuple("FW_VERSION",                DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::HW_VERSION,                 std::tuple("HW_VERSION",                DataFormatTypes<0>{}, DataFormat::Float, "[DISABLED]")),
    std::pair(SipmControlReadCommand::SERIAL_NUMBER,              std::tuple("SERIAL_NUMBER",             DataFormatTypes<0>{}, DataFormat::Int  , "[DISABLED]"))
);

CommandClass(SipmControlRead);
